#pragma once
#include <memory>
#include <optional>
#include "def.h"
#include "empty_node.h"
#include "unary_node.h"
#include "bin_node.h"
#include "val_node.h"
#include "var_node.h"
#include "array_node.h"
#include "func_node.h"
#include "range_node.h"
#include "string_node.h"