# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oster/Electrolisys

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oster/Electrolisys

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/oster/Electrolisys/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oster/Electrolisys/CMakeFiles /home/oster/Electrolisys//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oster/Electrolisys/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExternalDirectory

# Build rule for target.
ExternalDirectory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExternalDirectory
.PHONY : ExternalDirectory

# fast build rule for target.
ExternalDirectory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExternalDirectory.dir/build.make CMakeFiles/ExternalDirectory.dir/build
.PHONY : ExternalDirectory/fast

#=============================================================================
# Target rules for targets named PhysProperties

# Build rule for target.
PhysProperties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhysProperties
.PHONY : PhysProperties

# fast build rule for target.
PhysProperties/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/build
.PHONY : PhysProperties/fast

src/specificvolume.o: src/specificvolume.cpp.o
.PHONY : src/specificvolume.o

# target to build an object file
src/specificvolume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/specificvolume.cpp.o
.PHONY : src/specificvolume.cpp.o

src/specificvolume.i: src/specificvolume.cpp.i
.PHONY : src/specificvolume.i

# target to preprocess a source file
src/specificvolume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/specificvolume.cpp.i
.PHONY : src/specificvolume.cpp.i

src/specificvolume.s: src/specificvolume.cpp.s
.PHONY : src/specificvolume.s

# target to generate assembly for a file
src/specificvolume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/specificvolume.cpp.s
.PHONY : src/specificvolume.cpp.s

src/zone.o: src/zone.cpp.o
.PHONY : src/zone.o

# target to build an object file
src/zone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/zone.cpp.o
.PHONY : src/zone.cpp.o

src/zone.i: src/zone.cpp.i
.PHONY : src/zone.i

# target to preprocess a source file
src/zone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/zone.cpp.i
.PHONY : src/zone.cpp.i

src/zone.s: src/zone.cpp.s
.PHONY : src/zone.s

# target to generate assembly for a file
src/zone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/zone.cpp.s
.PHONY : src/zone.cpp.s

src/zonebound.o: src/zonebound.cpp.o
.PHONY : src/zonebound.o

# target to build an object file
src/zonebound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/zonebound.cpp.o
.PHONY : src/zonebound.cpp.o

src/zonebound.i: src/zonebound.cpp.i
.PHONY : src/zonebound.i

# target to preprocess a source file
src/zonebound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/zonebound.cpp.i
.PHONY : src/zonebound.cpp.i

src/zonebound.s: src/zonebound.cpp.s
.PHONY : src/zonebound.s

# target to generate assembly for a file
src/zonebound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhysProperties.dir/build.make CMakeFiles/PhysProperties.dir/src/zonebound.cpp.s
.PHONY : src/zonebound.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... ExternalDirectory"
	@echo "... PhysProperties"
	@echo "... src/specificvolume.o"
	@echo "... src/specificvolume.i"
	@echo "... src/specificvolume.s"
	@echo "... src/zone.o"
	@echo "... src/zone.i"
	@echo "... src/zone.s"
	@echo "... src/zonebound.o"
	@echo "... src/zonebound.i"
	@echo "... src/zonebound.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

