add_test( ArrayNode_test.SizeConstructor /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.SizeConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.SizeConstructor PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Insert_Back /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Insert_Back]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Insert_Back PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Insert /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Insert]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Insert PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Replace /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Replace]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Replace PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Begins /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Begins]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Begins PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Ends /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Ends]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Ends PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.CopyConstructor /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.CopyConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.CopyConstructor PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.MoveConstructor /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.MoveConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.MoveConstructor PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Move_SharedPtrVal_Constructor /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Move_SharedPtrVal_Constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Move_SharedPtrVal_Constructor PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Copy_SharedPtrVal_Constructor /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Copy_SharedPtrVal_Constructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Copy_SharedPtrVal_Constructor PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Operator_Eq_copy /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Operator_Eq_copy]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Operator_Eq_copy PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Operator_Eq_move /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Operator_Eq_move]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Operator_Eq_move PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Type_Numeric_Array /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Type_Numeric_Array]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Type_Numeric_Array PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Type_String_Array /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Type_String_Array]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Type_String_Array PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Type_Array /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Type_Array]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Type_Array PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.ExecuteCorrect /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.ExecuteCorrect]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.ExecuteCorrect PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.ExecuteError /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.ExecuteError]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.ExecuteError PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.ExecuteCorrect_id /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.ExecuteCorrect_id]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.ExecuteCorrect_id PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.ExecuteError_id /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.ExecuteError_id]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.ExecuteError_id PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Cached_Result /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Cached_Result]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Cached_Result PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Cached_Result_id /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Cached_Result_id]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Cached_Result_id PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.is_Numeric /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.is_Numeric]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.is_Numeric PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.is_String /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.is_String]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.is_String PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.is_Array /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.is_Array]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.is_Array PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Print_Text /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Print_Text]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Print_Text PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( ArrayNode_test.Print_Result /home/oster/OsterMath-Backend/bin/nodes_test [==[--gtest_filter=ArrayNode_test.Print_Result]==] --gtest_also_run_disabled_tests)
set_tests_properties( ArrayNode_test.Print_Result PROPERTIES WORKING_DIRECTORY /home/oster/OsterMath-Backend SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( nodes_test_TESTS ArrayNode_test.SizeConstructor ArrayNode_test.Insert_Back ArrayNode_test.Insert ArrayNode_test.Replace ArrayNode_test.Begins ArrayNode_test.Ends ArrayNode_test.CopyConstructor ArrayNode_test.MoveConstructor ArrayNode_test.Move_SharedPtrVal_Constructor ArrayNode_test.Copy_SharedPtrVal_Constructor ArrayNode_test.Operator_Eq_copy ArrayNode_test.Operator_Eq_move ArrayNode_test.Type_Numeric_Array ArrayNode_test.Type_String_Array ArrayNode_test.Type_Array ArrayNode_test.ExecuteCorrect ArrayNode_test.ExecuteError ArrayNode_test.ExecuteCorrect_id ArrayNode_test.ExecuteError_id ArrayNode_test.Cached_Result ArrayNode_test.Cached_Result_id ArrayNode_test.is_Numeric ArrayNode_test.is_String ArrayNode_test.is_Array ArrayNode_test.Print_Text ArrayNode_test.Print_Result)
